### ISSUE TITLE
app gets crashed every time

### ISSUE THREAD

**Issue by nikhilnanda02** [SubhamTyagi/android-ocr#4]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 19541 (AsyncTask #1), pid 19432 (subhamtyagi.ocr).

Please help what i am doing wrong

**Comment by SubhamTyagi** [comment]
Device:??
Android version:??

**Comment by PurpleCodingWizard** [comment]
I can confirm the same thing. I'm on android 10.
It keeps on prompting to download for missing data and does download some data But, fails and prompts again. If I try in this state the app crashes.
here's the bug report generated by android:

> java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: throw with null exception
	at io.github.subhamtyagi.ocr.MainActivity$f.doInBackground(:7)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by voxitme** [comment]
Same as @nikhilnanda02 here, crashing when clicking on the "crop" button.
Oneplus 6 - Lineage 17.1 (android 10)
Here is the log
[2020-09-23-17-16-19.txt](https://github.com/SubhamTyagi/android-ocr/files/5269156/2020-09-23-17-16-19.txt)

**Comment by voxitme** [comment]
@PurpleCodingWizard one of your issues is https://github.com/SubhamTyagi/android-ocr/issues/3

**Comment by SubhamTyagi** [comment]
could you test new version

https://github.com/SubhamTyagi/android-ocr/releases/download/v1.1/app-arm64-v8a-release.apk

**Comment by PurpleCodingWizard** [comment]
Not OP but all issues are resolved. I tried v1.2 arm7a release APK from github.

**Comment by SubhamTyagi** [comment]
fixed
