### ISSUE TITLE
Not usable running Android 12

### ISSUE THREAD

**Issue by vArNi0101** [SubhamTyagi/android-ocr#40]
I just heard about this app, installation and initial start was successful. After downloading the training data, app crashed. Now I was not able to open the app  anymore. 

Device: Google Pixel 4a
Android version 12 (build SQ1A.211205.008)

**Comment by ignacio-agullo** [comment]
Installed it on Samsung Galaxy S10+ with Android 12 this evening. Tried it with no crash, but no results either.  No matter where I pick the image from (camera, gallery or files), after selecting it the image area gets darker and then nothings seems to happen.  Same thing with pre-process disabled.  I tap the "clock" icon and I always get the message "No text could be recognized".

**Comment by rhayy** [comment]
I have the same experience as @vArNi0101.
The app is running as long as I don't requet the trained data.
Once it does so (or tries to do so), the app crashes and can no more be opened.
I have managed to track the issue :

msg: java.lang.ArrayIndexOutOfBoundsException: length=130; index=-1
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.subhamtyagi.ocr/io.github.subhamtyagi.ocr.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=130; index=-1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=130; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at io.github.subhamtyagi.ocr.MainActivity.y(Unknown Source:8)
	at io.github.subhamtyagi.ocr.MainActivity.x(Unknown Source:31)
	at io.github.subhamtyagi.ocr.MainActivity.z(:15)
	at io.github.subhamtyagi.ocr.MainActivity.onCreate(:4)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1315)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
	... 11 more 

My device's ROM is Havoc 4.13 (Android 11).

**Comment by SomeMichael** [comment]
Also does not work on my Samsung A32 5G. Downloads training data again and again. It does not even request any rights …?

**Comment by rugk** [comment]
See https://github.com/SubhamTyagi/android-ocr/issues/67 if you are affected by that. As this has been said to be a dupe, make sure to not select multiple languages, the app (apparently reproducible) crashes if you do so. It should work with one language though.
